![NumPy logo](https://static.javatpoint.com/tutorial/numpy/images/numpy-tutorial.png)

NumPy is the fundamental package for scientific computing with Python. It is short for **numerical python**.

It contains among other things:
* a powerful N-dimensional array object
* mathematical functions which operate on these arrays 
* useful linear algebra, Fourier transform, and random number capabilities

The NumPy array object is the common interface for working with typed arrays of data across a wide-variety of scientific Python packages. It's a very popular dependency. 


### Some Additional Nomenclature

| Programming Name | Definition | Example |
|---|---|---|
| Array | Ordered collection of data items | timestamps for Oct 1, 2019 |
| Vector | 1 dimensional array | temperature data for Newark, DE |
| Matrix | 2 dimensional array | tree cover density of USA at 1km resolution |


# NumPy Arrays (ndarray)

The basic type in NumPy is the N-dimensional array class, **ndarray**.  A NumPy array represents a *contiguous* block of memory holding elements of the same type. The attributes of the array define how the elements are aranged in memory.


|Numpy Function| Use|
|--|--|
|`np.sum()`| Sum all numbers in a list/array.
|`np.sin()`, `np.cos()`, `np.tan()`| Trig functions
|`np.max()`, `np.min()`| Find max or min value in list/array
|`np.mean()`, `np.median()`| Find mean or median value in list/array
|`np.sqrt()`| Square Root the values
|`np.shape()`|Return the shape of an array|
|`np.zeros([n,n])`|An array of zeros with size nxn|
|`np.ones([n,n])`|An array of ones with size nxn|
|`np.linspace(start, end, n)`|Array of evenly spaced numbers between start and end|
|`np.range(start, end, step)`|Range of numbers as a list|
|`np.arange(start, stop, step)`|Range of numbers as an array|
| `np.rint()` | Round floats to nearest integer |
|...|...|

Note: If you give the numpy function a list, it will convert it to a numpy array for you, e.g., `np.array([1,2,3,4])`



In [2]:
import numpy as np   # standard import abbreviation

In [2]:
a = np.array([1, 2, 3])  # a NumPy array of three integers
a

array([1, 2, 3])

In [3]:
a.shape  # tuple representing the size of each dimension

(3,)

In [4]:
a.ndim  # number of dimensions

1

In [5]:
a.dtype  # Data type information

dtype('int64')

In [6]:
b = np.array([1., 2., 3., 4.])  # a NumPy array of four floats

In [7]:
b.shape

(4,)

In [8]:
b.dtype

dtype('float64')

NumPy provides various functions for creating common arrays

In [9]:
a = np.arange(10)  # a range of values from (0) to 10
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [10]:
a = np.arange(1, 10, 2, dtype='float32')
print(a)
print(a.dtype)

[ 1.  3.  5.  7.  9.]
float32


In [11]:
a = np.linspace(0, 10, 5)  # 5 linearly spaced entries from 0 to 10 
print(a)

[  0.    2.5   5.    7.5  10. ]


In [3]:
# Convert degrees to radians
np.radians(90)

1.5707963267948966

In [4]:
# Conver radians to degrees
np.degrees(1.5707963267948966)

90.0

In [ ]:
# Special "not a number" value
np.nan

Note that np.nan is equivalent to NA in R. When working with numpy (which is most of the time), np.nan is THE way to declare a NAN in python.

# Exercise

1) Convert the following degree list to radians using a for loop.

deg_list = [15,36,45,88,90]

rad_list = ?


#####

## Array operations

Mathematical operations can be performed on NumPy arrays.  The operations is applied element-by-element to the entire array.

In [12]:
a = np.array([1, 2, 3])
b = np.array([6, 7, 8])

In [13]:
a + b

array([ 7,  9, 11])

In [14]:
a * b

array([ 6, 14, 24])

But could that be done with lists?  Look at the difference...

In [6]:
a = [1, 2, 3]
b = [6, 7, 8]

In [7]:
a + b

[1, 2, 3, 6, 7, 8]

If we want to add lists the same way we just did with arrays, here is how you would do that

In [16]:
c = [i+j for i, j in zip(a, b)]
print(c)

[7, 9, 11]


NumPy provides many mathematical functions which operate on arrays.

In [4]:
a = np.linspace(-np.pi, np.pi, 10)# Return evenly spaced numbers over a specified interval.

a

array([-3.14159265, -2.44346095, -1.74532925, -1.04719755, -0.34906585,
        0.34906585,  1.04719755,  1.74532925,  2.44346095,  3.14159265])

In [18]:
np.sin(a)

array([ -1.22464680e-16,  -6.42787610e-01,  -9.84807753e-01,
        -8.66025404e-01,  -3.42020143e-01,   3.42020143e-01,
         8.66025404e-01,   9.84807753e-01,   6.42787610e-01,
         1.22464680e-16])

In [19]:
np.cos(a)

array([-1.        , -0.76604444, -0.17364818,  0.5       ,  0.93969262,
        0.93969262,  0.5       , -0.17364818, -0.76604444, -1.        ])

## Multiple dimensions

NumPy arrays can also be multidimentional.

In [20]:
a = np.arange(12).reshape(3, 4)  # create a 2 dimensional array with dimensions of 3 and 4
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [21]:
a.ndim # find the number of dimensions of array a

2

In [22]:
a.shape # find the shape of array a

(3, 4)

In [23]:
2 * a

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

## Indexing and Slicing

Like Python lists, arrays can be indexed and sliced.

In [24]:
a = np.arange(10)

In [25]:
a[3]

3

In [26]:
a[2:-2]

array([2, 3, 4, 5, 6, 7])

In [27]:
a[1::2]

array([1, 3, 5, 7, 9])

Multidimentional arrays can also be sliced.  A comma seperates the dimensions.

Noice that we are using .reshape() to "rearrange" the numpy array of 12 values ranging from 0 to 11. We reshape it to 3 rows and 4 columns or (3,4) . 

In [28]:
b = np.arange(12).reshape(3, 4)
print(b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [29]:
b[1, 2]

6

In [30]:
b[2]  # select the entire second dimension

array([ 8,  9, 10, 11])

In [31]:
b[1:3, :3]  # slices are also allowed

array([[ 4,  5,  6],
       [ 8,  9, 10]])

In [32]:
b[:, 2]  # all elements in the first dimension

array([ 2,  6, 10])

In [33]:
# ... (ellipsis) will replace one or more dimensions
b[..., 2]

array([ 2,  6, 10])

# Exercises

2) Create a null vector (1-d array) of size 10

3) Create a null vector (1-d array) of size 10 but with the fifth value being 1

4) Create a vector with values ranging from 10 to 49

5) Reverse a vector (first element becomes the last)




######

### Logical indexing

Logical indexing allow selecting elements from an array using an array of `True` and `False` values.  Often this is array is not implicitly specified.  

In [34]:
a = np.arange(5)

In [35]:
selection = np.array([True, False, False, True, True])
a[selection]

array([0, 3, 4])

In [36]:
a[a>2]

array([3, 4])

## Masked Arrays

Masked arrays are a specialization of NumPy arrays to handle flagging elements that should be ignored. This allows for the elimination of values from computations.

This is great for ignoring bad values but keeping the shape of the array you want. 

In [37]:
a = np.ma.arange(12).reshape(3, 4)
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [38]:
a[2,2] = np.ma.masked
print(a)

[[0 1 2 3]
 [4 5 6 7]
 [8 9 -- 11]]


In [39]:
b = a * 2
print(b)

[[0 2 4 6]
 [8 10 12 14]
 [16 18 -- 22]]


In [40]:
# logical masking
a[a > 6] = np.ma.masked
print(a)

[[0 1 2 3]
 [4 5 6 --]
 [-- -- -- --]]


In [41]:
# unmasked an element
a[-1, -1] = 42
print(a)

[[0 1 2 3]
 [4 5 6 --]
 [-- -- -- 42]]


## Exercises

6) Create a 3x3 matrix with values ranging from 0 to 8. Multiply by 2. 

7) Mask the all values less than 3 in the matrix formed above. 

8) Given the list of l=[-.7, -1.5, 14, 0.3, 1, 1.8, 5] , convert to array and mask all values greater than 1.
